bucketweb:
  enabled: true
compactor:
  enabled: true
existingObjstoreSecret: thanos-objstore-config
existingObjstoreSecretItems:
- key: thanos.yaml
  path: objstore.yml
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
minio:
  auth:
    rootUser: minio
    rootPassword: minio123
  defaultBuckets: thanos
  enabled: true
  
query:
  dnsDiscovery:
    sidecarsNamespace: monitoring
    sidecarsService: prometheus-kube-prometheus-thanos-discovery
ruler:
  alertmanagers:
  - http://prometheus-kube-prometheus-alertmanager.monitoring.svc.cluster.local:9093
  config: |-
    groups:
      - name: "metamonitoring"
        rules:
          - alert: "PrometheusDown"
            expr: absent(up{prometheus="monitoring/kube-prometheus"})
  enabled: true
storegateway:
  enabled: true
